# The programs.trollshell options shared by the NixOS and home-manager modules,
# so enable/package/weather.fallbackCity stay declared in one place instead of
# drifting between two near-identical copies. Each module imports this and adds
# its own platform-specific options (geoclue system-side, systemd user service
# home-side) plus the matching config.
self:
{
  config,
  lib,
  pkgs,
  ...
}:
{
  # Point the module system at the real source file so evaluation errors and
  # the autogenerated options doc's "Declared by" links name `module-common.nix`
  # rather than `<unknown-file>` (these modules are imported as applied
  # functions, `import ./module-common.nix self`, which otherwise loses the
  # path).
  _file = "nix/module-common.nix";

  # A stable module key so the several `import ./module-common.nix self` call
  # sites — the NixOS module, the home-manager module, and the `options-doc`
  # evaluation in flake.nix that merges *both* platform modules at once —
  # collapse to a single declaration. Without it, merging the two modules in one
  # `evalModules` (as the options-doc build does) trips "option declared multiple
  # times", since each platform module re-imports this shared base. Harmless to
  # the two real modules, which each import this exactly once.
  key = "trollshell-module-common";

  options.programs.trollshell = {
    enable = lib.mkEnableOption "trollshell — hytte-based Wayland desktop shell";

    package = lib.mkOption {
      type = lib.types.package;
      default = self.packages.${pkgs.stdenv.hostPlatform.system}.trollshell;
      defaultText = lib.literalExpression "trollshell.packages.\${system}.trollshell";
      description = "The trollshell package to install.";
    };

    # The control-center companion app (#399): an external GTK4/libadwaita
    # settings & management UI (app-id mov.vibec0re.trollshell.ControlCenter)
    # that talks to the running shell's mov.vibec0re.trollshell.Control
    # session-bus endpoint. It's a separate binary from the shell, so it gets
    # its own toggle + package option here in the shared base — both the NixOS
    # and home-manager modules install it (system packages / user profile).
    controlCenter = {
      enable = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = ''
          Install the trollshell-control-center companion app alongside the
          shell. It's the external settings/management window (launchable by its
          app-id, mov.vibec0re.trollshell.ControlCenter) that speaks to the
          running shell's Control session-bus endpoint. Enabled by default; set
          false to drop it (the shell itself doesn't depend on it).
        '';
      };

      package = lib.mkOption {
        type = lib.types.package;
        default = self.packages.${pkgs.stdenv.hostPlatform.system}.trollshell-control-center;
        defaultText = lib.literalExpression "trollshell.packages.\${system}.trollshell-control-center";
        description = "The trollshell-control-center package to install.";
      };
    };

    weather.fallbackCity = lib.mkOption {
      type = lib.types.nullOr lib.types.str;
      default = null;
      example = "Berlin";
      description = ''
        City the weather widget falls back to when geolocation is unavailable.
        Sets TROLLSHELL_WEATHER_CITY for the session. Leave null to rely on
        geoclue (enabled system-side by the NixOS module).
      '';
    };

    ownerName = lib.mkOption {
      type = lib.types.nullOr lib.types.str;
      default = null;
      example = "Jordan";
      description = ''
        Name (or descriptor) the desktop owner goes by, for LLM plugin
        personas (pet, caw) to refer to. Sets TROLLSHELL_OWNER for the
        session, read by both through the shared
        `hytte_ai_providers::owner()` resolver. Leave null to fall back to
        each plugin's neutral default ("your human").
      '';
    };

    stats.layout = lib.mkOption {
      type = lib.types.enum [
        "combined"
        "multicolumn"
        "split"
      ];
      default = "multicolumn";
      example = "combined";
      description = ''
        How the System Stats drawer page arranges its five resource cards
        (CPU / Memory / Disks / GPU / Services). Sets TROLLSHELL_STATS_LAYOUT
        for the session, read once at shell startup.

        This is the shell's first purely-cosmetic layout knob (issue #508). The
        design principle is otherwise "composable, not configurable" — the shell
        is wired in Rust, not config — so most appearance choices are made in
        `main.rs`, not here. The Stats layout is the deliberate exception,
        blessed on the #508 thread, because the combined and split shapes both
        have real users.

        - `multicolumn` (default): the same five cards in a two-column grid —
          CPU beside Memory, Disks beside GPU, Services spanning both columns
          underneath. Uses a wider drawer clamp (~1080px vs. the usual 680px)
          so the two side-by-side history graphs each keep a usable width.
          Chips still open this one page, scrolled to their card.
        - `combined`: all five cards stacked in one scrolling page. The
          original pre-#307 shape, restored by #518 after #307 had split it.
          Clicking any resource bar chip opens this page scrolled to that card
          (the #516/#547 deep-links).
        - `split`: five separate single-card pages, one per bar chip — #307's
          shape (filed by kaesaecracker), resurrected here alongside the
          combined page so it is a declarative option rather than a fork patch.
          Each chip opens only its own resource's page.

        An unrecognized value falls back to `multicolumn` (the enum type
        rejects one at evaluation time; the runtime fallback covers a hand-set
        env var).
      '';
    };

    wallpaper.backend = lib.mkOption {
      type = lib.types.enum [
        "swaybg"
        "awww"
        "none"
      ];
      default = "swaybg";
      example = "awww";
      description = ''
        Which wallpaper daemon trollshell manages for the session, and what the
        Appearance picker tells to reload. One enum value drives the daemon
        wiring and the `reloadCommand` default together, so two daemons can never
        run at once — backend selection is structural, not an assertion.

        - `swaybg` (default — today's behavior): the bundled swaybg user unit;
          the Appearance picker restarts it (the shell's built-in default), so
          `reloadCommand` stays null.
        - `awww`: the swww successor (upstream renamed swww → awww at 0.12; swww
          itself is deprecated). Defaults `reloadCommand` to `awww img {}`. The
          daemon is run by home-manager's `services.awww`; the NixOS module only
          exports the reload command (a NixOS-only user without home-manager
          runs the awww daemon themselves).
        - `none`: manage no daemon at all — the Appearance picker only writes
          `~/.config/trollshell/wallpaper.path` (and runs `reloadCommand` if you
          set one yourself). Use this to wire your own daemon.

        The legacy `programs.trollshell.swaybg.enable` (home-manager) and a
        hand-set `wallpaper.reloadCommand` both still work and take precedence;
        they are gently deprecated in favor of this enum.
      '';
    };

    wallpaper.reloadCommand = lib.mkOption {
      type = lib.types.nullOr lib.types.str;
      # Per backend (`awww img {}` for awww). An option default, so any explicit
      # `reloadCommand = "…"` the user sets already wins over it (defaults are the
      # lowest merge priority). `{}` is the shell-quoted path, NOT a $VAR.
      default =
        {
          swaybg = null;
          awww = "awww img {}";
          none = null;
        }
        .${config.programs.trollshell.wallpaper.backend};
      defaultText = lib.literalExpression ''# per backend: null (swaybg/none) or "awww img {}" (awww)'';
      example = "awww img {}";
      description = ''
        Shell command the Appearance picker runs (via `sh -c`) after writing
        `~/.config/trollshell/wallpaper.path`, to tell your wallpaper daemon to
        reload. A `{}` in the command is replaced with the chosen path,
        shell-quoted. Sets TROLLSHELL_WALLPAPER_RELOAD_CMD for the session.

        Use the `{}` placeholder, not a `$VAR` reference: this value is delivered
        through sessionVariables, which expands `$`-references at login (before
        the path exists), so `awww img "$TROLLSHELL_WALLPAPER_PATH"` would expand
        to `awww img ""`. The path is still also exported as
        TROLLSHELL_WALLPAPER_PATH for daemons that read it directly.

        Defaults follow `wallpaper.backend`: null for `swaybg` (restart the
        bundled swaybg unit — the shell's built-in default) and `none`, and
        `awww img {}` for `awww`. Set it explicitly to override; an explicit
        value wins over the per-backend default.
      '';
    };

    # Night-light (color temperature) via a wlsunset user unit. The shell only
    # toggles the unit on/off (nightlight.rs, mirroring the wallpaper picker's
    # zero-state daemon playbook); these options parameterise the unit's
    # ExecStart. The unit itself is declared home-manager-side (nix/hm-module.nix)
    # alongside the swaybg unit — it is a per-user wlr-gamma-control daemon, not a
    # system service.
    #
    # Since #577 the coordinates are resolved at *toggle* time by the shell, not
    # at nix-eval time: lat/lon below win when set (configuring them is an
    # explicit statement of where you are), and otherwise the live location fix
    # is used (GeoClue2, which ships with enableRecommendedServices). Leaving
    # both null is therefore a working configuration, not an inert one — on
    # home-manager.
    #
    # These four options are declared here, in the shared base, purely so the
    # generated options doc has one page rather than a fork. They are HOME-
    # MANAGER-ONLY: the NixOS module (nix/nixos-module.nix) declares no
    # wlsunset package or unit and has no toggle target to drive, so on a
    # NixOS-only deployment (no home-manager) setting any of them evaluates
    # but does nothing — the Appearance panel's Night light switch still
    # renders (the shell registers the service unconditionally) and silently
    # no-ops. nixos-module.nix asserts on this rather than letting it happen
    # quietly (#657); this comment and the four descriptions below say so too,
    # since the descriptions are what `nixos-option` / the rendered options
    # doc actually show a NixOS reader.
    nightlight = {
      latitude = lib.mkOption {
        type = lib.types.nullOr (lib.types.either lib.types.float lib.types.str);
        default = null;
        example = 52.52;
        description = ''
          Latitude in decimal degrees for wlsunset's geo (sunrise/sunset) mode
          (`wlsunset -l <latitude>`). Optional. When set (together with
          `longitude`) it takes precedence over the live location fix, so use it
          to pin night light to a fixed place, or if you do not run GeoClue2.
          Leave both null to follow the live fix instead. With neither a fix nor
          these set, the toggle refuses to start the daemon and logs why. May be
          given as a float (52.52) or a string ("52.52").

          Home-manager only (#657): the wlsunset unit this parameterises is
          declared by the home-manager module (`nix/hm-module.nix`). Setting it
          through the NixOS module alone has no effect — there is no unit for
          it to reach — and trips an assertion there rather than silently
          no-op'ing.
        '';
      };

      longitude = lib.mkOption {
        type = lib.types.nullOr (lib.types.either lib.types.float lib.types.str);
        default = null;
        example = 13.405;
        description = ''
          Longitude in decimal degrees for wlsunset's geo mode
          (`wlsunset -L <longitude>`). Optional, and only used together with
          `latitude` — a half-configured pair is ignored (see `latitude`). May
          be a float or a string.

          Home-manager only (#657): see `latitude`'s description — the NixOS
          module has no wlsunset unit for this to reach.
        '';
      };

      dayTemp = lib.mkOption {
        type = lib.types.int;
        default = 6500;
        example = 6500;
        description = ''
          Daytime color temperature in kelvin (`wlsunset -T <dayTemp>`). 6500K is
          neutral daylight (wlsunset's own default).

          Home-manager only (#657): see `latitude`'s description — the NixOS
          module has no wlsunset unit for this to reach.
        '';
      };

      nightTemp = lib.mkOption {
        type = lib.types.int;
        default = 4000;
        example = 3500;
        description = ''
          Nighttime color temperature in kelvin (`wlsunset -t <nightTemp>`).
          Lower is warmer; 4000K is a gentle warm-white.

          Home-manager only (#657): see `latitude`'s description — the NixOS
          module has no wlsunset unit for this to reach.
        '';
      };
    };

    # The Claude bridge (#584/#694): a keyless, loopback-only OpenAI-compatible
    # shim in front of headless Claude Code (`claude --print`), so the
    # LLM-backed plugins can ride a Claude Code subscription instead of a
    # metered provider — `hytte_ai_providers::Provider` is just a base URL, so
    # pointing a plugin at http://127.0.0.1:<port> is the whole integration.
    #
    # HOME-MANAGER-ONLY, same reasoning nightlight documents above (#657): the
    # bridge is rendered by nix/hm-module.nix, and a NixOS-only deployment has no
    # per-user `claude` login state for the bridge to drive. Setting these
    # through the NixOS module alone trips an assertion there rather than
    # silently no-op'ing.
    #
    # SINCE #866 THE BRIDGE IS A PLUGIN, NOT A UNIT. The home-manager module no
    # longer declares systemd.user.services.trollshell-claude-bridge; it renders
    # `programs.trollshell.plugins.claude-bridge` instead, so the daemon is
    # launched by the shell's own plugin launcher as a transient
    # trollshell-plugin-claude-bridge.service. The options below are unchanged
    # (`mode` is the one addition) and keep meaning exactly what they meant.
    #
    # Option granularity follows @kaesaecracker's rule on #694 — "anything that
    # should be an option should get an option; everything that is not obviously
    # user defined could be overridden in the service cfg". So `port` (two
    # things must agree on one number), `model` and `timeoutSeconds` (both
    # documented footguns, see below) are first class. `mode` joined them in #866
    # because it is no longer merely an env knob: it decides whether the rendered
    # plugin entry may declare the `anthropic` secret slot at all (see below).
    # The remaining env knobs — CLAUDE_BRIDGE_THINKING, CLAUDE_BRIDGE_STATE_DIR,
    # RUST_LOG — stay reachable through the plugin entry's own `env`, which is
    # where every other plugin's knobs live:
    #
    #   programs.trollshell.plugins.claude-bridge.env.CLAUDE_BRIDGE_THINKING = "auto";
    #
    # (the module sets its own env values with `lib.mkDefault`, so a plain
    # definition there wins over them). That replaces the pre-#866 escape hatch,
    # `systemd.user.services.trollshell-claude-bridge.Service.Environment`, which
    # has nothing left to attach to now that there is no unit — a `PATH=` override
    # for a `claude` outside the user manager's PATH goes in the same place. The
    # full inventory is the table in crates/hytte-claude-bridge/src/main.rs and
    # the comment block in etc/systemd/user/trollshell-claude-bridge.service.
    claudeBridge = {
      enable = lib.mkEnableOption ''
        the hytte-claude-bridge daemon (#584): a keyless loopback
        OpenAI-compatible shim over headless Claude Code, so the LLM-backed
        plugins (pet, caw) can ride a Claude Code subscription with no code
        change — point one at it with
        `plugins.pet.env.PET_LLM_URL = "http://127.0.0.1:8787"`.

        Since #866 this renders as a **plugin entry**, not a hand-declared
        systemd unit: enabling it defines `plugins.claude-bridge`, so the shell's
        launcher spawns it as a transient `trollshell-plugin-claude-bridge`
        service, the control-center's Plugins tab can stop and start it, and it
        gets keyring secret injection like any other plugin. The daemon also
        paints a small status chip on the bar (mode, whether a credential is
        held, coarse request health).

        **The shell is what starts it.** The retired unit carried
        `WantedBy = <session target>` and came up on its own; a plugin entry is
        launched by `trollshell`'s launcher at startup instead, so with the shell
        disabled or crash-looping nothing brings the bridge up and anything
        pointed at `127.0.0.1:<port>` gets a connection refused. Once launched it
        does outlive the shell — the transient unit is `PartOf` the session
        target, not the shell — so `systemctl --user restart trollshell` leaves
        the endpoint answering with only the chip gone. If you need the bridge
        without the shell, run it from
        `etc/systemd/user/trollshell-claude-bridge.service` by hand and leave
        this option off; do not do both (see the note under `mode`).

        Prerequisites the module cannot provide for you: the `claude` CLI must
        be resolvable on the *systemd user manager's* PATH (on NixOS that is the
        system profile plus your per-user profile — so a `claude` in
        `home.packages` is found, one installed by npm into `~/.local/bin` is
        not), and it must already be logged in (`claude` → `/login`). The bridge
        holds no credentials of its own.

        Home-manager only (#657 precedent): the NixOS module declares no unit
        for this and asserts rather than silently ignoring it
      '';

      package = lib.mkOption {
        type = lib.types.package;
        default = self.packages.${pkgs.stdenv.hostPlatform.system}.hytte-claude-bridge;
        defaultText = lib.literalExpression "trollshell.packages.\${system}.hytte-claude-bridge";
        description = "The hytte-claude-bridge package the user service runs.";
      };

      port = lib.mkOption {
        type = lib.types.port;
        default = 8787;
        example = 8788;
        description = ''
          Loopback port the bridge listens on (`CLAUDE_BRIDGE_PORT`). The
          address is not configurable — it is always 127.0.0.1.

          A first-class option rather than an env line because two things have
          to agree on one number: this, and the `*_LLM_URL` of every plugin
          pointed at the bridge (`plugins.pet.env.PET_LLM_URL`).

          8787, not 8080 — 8080 belongs to `petBrain` below (the llama-server
          brain), and the two backends are meant to be swappable, not exclusive.
        '';
      };

      mode = lib.mkOption {
        type = lib.types.enum [
          "subscription"
          "reprompt"
          "api"
        ];
        default = "subscription";
        example = "api";
        description = ''
          Which backend answers (`CLAUDE_BRIDGE_MODE`, #730):

          - `subscription` (the default) — one persisted, title-addressed
            `claude` session per conversation; resumed turns carry only the
            delta, which is what keeps the prompt prefix cache warm.
          - `reprompt` — a fresh one-off `claude` per turn, with the bridge
            holding the transcript.
          - `api` — the Anthropic Messages API, **billed per token**. No
            `claude` child is spawned at all.

          This is a first-class option rather than a plain env line because it
          decides one thing nix has to get right on your behalf (#866): the
          `anthropic` **secret slot** is declared on the rendered plugin entry
          *only* in `api` mode. In the two `claude` modes an `ANTHROPIC_API_KEY`
          in the environment is a **startup refusal**, not a credential — it
          would silently move the child off your subscription and onto metered
          credits, so `crates/hytte-claude-bridge/src/envguard.rs` fails closed
          on it and names the variable in `systemctl status` (#752). Declaring
          the slot there would therefore stop the bridge starting the moment you
          stored a key for anything.

          In `api` mode the key comes from your login keyring (store it in the
          control-center's AI Keys tab under the `anthropic` slot); the launcher
          injects it as `ANTHROPIC_API_KEY` at spawn, which the bridge reads
          before falling back to `~/.config/trollshell/anthropic.key`. That file
          keeps working, and is still the only source under the hand-installed
          static unit, which scrubs the variable.

          The retired unit's `UnsetEnvironment=` scrub is carried across, not
          dropped: a transient unit has no such setting, so the home-manager
          module renders the same four billing-redirect variables as **empty**
          entries in the plugin's `env` instead. Empty reads as "not set" to
          every consumer — envguard does not trip, the key file is still
          consulted — and the launcher appends injected secrets *after* the
          declared env, so `api` mode's keyring key still wins. Both layers are
          therefore intact: the scrub, and the startup refusal behind it.

          One deployment note: `etc/systemd/user/trollshell-claude-bridge.service`
          is a *different* unit name from the transient
          `trollshell-plugin-claude-bridge` the launcher creates, so the launcher
          cannot see the pair. Running both means two bridges and the second
          failing to bind the port. Pick one.
        '';
      };

      model = lib.mkOption {
        type = lib.types.nullOr lib.types.str;
        default = null;
        example = "claude-haiku-4-5";
        description = ''
          The model the bridge asks `claude` for (`CLAUDE_BRIDGE_MODEL`, i.e.
          `claude --model`). Null leaves it unset, which is *not* neutral: the
          child then runs on whatever `~/.claude/settings.json` picks — usually
          Opus — while the bridge's own per-request budget is only
          `timeoutSeconds` (8s by default, and it must stay under the client's
          10s global timeout). An Opus turn will routinely blow that budget and
          come back to the plugin as a 504.

          So pin something fast here if you want replies rather than fallbacks:
          `claude-haiku-4-5` is the value #694's reporter settled on for the pet.
          Leave it null only if you have deliberately raised `timeoutSeconds`
          (and the consuming plugin's own timeout with it — see
          `timeoutSeconds`).
        '';
      };

      timeoutSeconds = lib.mkOption {
        type = lib.types.ints.positive;
        default = 8;
        example = 20;
        description = ''
          The bridge's per-request budget in whole seconds
          (`CLAUDE_BRIDGE_TIMEOUT_SECS`, #699). A turn that overruns it comes
          back as a clean 504 the caller can fall back from.

          **Ordering invariant**: this must stay strictly *under* the consuming
          plugin's own global request timeout, or a slow turn tears the
          connection mid-read instead of returning a 504. That client budget is
          `hytte_ai_providers::DEFAULT_TIMEOUT` — 10 seconds — unless the plugin
          raises it; today only the pet has a knob for that
          (`plugins.pet.env.PET_LLM_TIMEOUT_SECS`, #711). The default 8 < 10
          satisfies it out of the box, and the home-manager module asserts the
          pair at evaluation time when both are declared, so raising this
          without raising the pet's fails the build rather than the request.
        '';
      };
    };

    # The pet's brain (#276): a local llama-server from nixpkgs' `llama-cpp`,
    # holding a small chat model resident. The pet plugin is a thin HTTP client
    # to it — the shell's daemon-as-state-store stance applied to a cat. It is
    # the other thing `plugins.pet.env.PET_LLM_URL` can point at, and the
    # alternative to `claudeBridge` above rather than a companion to it.
    #
    # Same home-manager-only caveat as claudeBridge: the unit is declared in
    # nix/hm-module.nix and the NixOS module asserts instead of ignoring these.
    #
    # llama-server takes no environment configuration at all, so the escape
    # hatch for everything not promoted to an option here is `extraArgs` below
    # rather than a `Service.Environment` override.
    petBrain = {
      enable = lib.mkEnableOption ''
        the trollshell-pet-brain user service (#276): a local `llama-server`
        (nixpkgs' llama-cpp) holding a small chat model resident for the pet
        plugin to talk to. Point the pet at it with
        `plugins.pet.env.PET_LLM_URL = "http://127.0.0.1:8080"`.

        You still have to fetch the model yourself — it is a multi-hundred-MB
        GGUF, not something to bake into a nix closure. Any chat-tuned GGUF
        works (the pet only ever sends /v1/chat/completions):

        ```
        mkdir -p ~/.local/share/trollshell-pet
        curl -L -o ~/.local/share/trollshell-pet/brain.gguf \
          'https://huggingface.co/openbmb/MiniCPM5-1B-GGUF/resolve/main/MiniCPM5-1B-Q4_K_M.gguf'
        ```

        Home-manager only (#657 precedent), like `claudeBridge` above
      '';

      package = lib.mkOption {
        type = lib.types.package;
        default = pkgs.llama-cpp;
        defaultText = lib.literalExpression "pkgs.llama-cpp";
        description = ''
          The package providing `llama-server`. Swap it for a build with the
          acceleration you actually have (e.g.
          `pkgs.llama-cpp.override { cudaSupport = true; }`) — the unit calls
          the `llama-server` binary out of this package by name, not
          `meta.mainProgram`.
        '';
      };

      port = lib.mkOption {
        type = lib.types.port;
        default = 8080;
        example = 8081;
        description = ''
          Port llama-server listens on (`--port`). First class for the same
          reason `claudeBridge.port` is: the pet's `PET_LLM_URL` has to name the
          same number. 8080 is llama-server's own default and is deliberately
          distinct from `claudeBridge.port` (8787) so both backends can be
          declared at once and swapped by editing one URL.
        '';
      };

      model = lib.mkOption {
        type = lib.types.nullOr lib.types.str;
        default = null;
        defaultText = lib.literalExpression ''"''${config.home.homeDirectory}/.local/share/trollshell-pet/brain.gguf"'';
        example = "/srv/models/qwen3-1.7b-q4.gguf";
        description = ''
          Absolute path to the GGUF the brain loads (`--model`). A plain string,
          not a nix path: the file is fetched at runtime into your home
          directory (see `enable`), and making it a path would copy hundreds of
          megabytes into the nix store on every rebuild.

          Null means `$HOME/.local/share/trollshell-pet/brain.gguf`, the
          location the download snippet in `enable` writes to and the one
          `etc/systemd/user/trollshell-pet-brain.service` has always used. The
          unit refuses to start (rather than crash-looping) while the file is
          absent, so declaring this before downloading the model is safe.
        '';
      };

      extraArgs = lib.mkOption {
        type = lib.types.listOf lib.types.str;
        default = [
          "--ctx-size"
          "1024"
          "--threads"
          "4"
        ];
        example = [
          "--ctx-size"
          "4096"
          "--threads"
          "8"
          "--n-gpu-layers"
          "99"
        ];
        description = ''
          The rest of `llama-server`'s argument vector, appended after
          `--model` and `--port`. This is the escape hatch for this unit —
          llama-server reads no environment configuration, so unlike
          `claudeBridge` there is no `Service.Environment` override to fall back
          on and the knobs have to come through here.

          The default mirrors
          `etc/systemd/user/trollshell-pet-brain.service`: a 1024-token context
          on 4 threads, sized for a ~1B Q4 model on a laptop. Setting this
          replaces the default outright rather than adding to it.
        '';
      };
    };

    recorder.audioByDefault = lib.mkOption {
      type = lib.types.bool;
      default = false;
      example = true;
      description = ''
        Whether the screen-recording chip (#403,
        crates/hytte-services/src/recorder.rs) starts with audio capture armed.
        This is only the *initial* value of the in-shell audio toggle, read once
        at service start; the toggle in Settings still flips it live during a
        session. Off by default (recordings are silent unless you opt in). When
        true, sets `TROLLSHELL_RECORD_AUDIO=1` for the session; that env var is
        the override, so leaving this at the default lets a hand-set
        `TROLLSHELL_RECORD_AUDIO` still win.
      '';
    };

    plugins = lib.mkOption {
      type = lib.types.attrsOf (
        lib.types.submodule {
          options = {
            enable = lib.mkOption {
              type = lib.types.bool;
              default = true;
              example = false;
              description = ''
                Whether the shell launches this plugin at startup (#419).
                A disabled entry is still *declared* — written to the launch
                state as "enabled": false, so it lists in the control-center's
                Plugins tab and can be started manually — it just doesn't
                auto-launch. Lets a downstream module switch a single entry
                off (`plugins.pet.enable = false;`) without removing its
                definition.
              '';
            };

            package = lib.mkOption {
              type = lib.types.package;
              description = ''
                The plugin's package (its out-of-process binary, built on
                hytte-plugin — never linked into the shell). The shell
                launches it as a transient trollshell-plugin-<id> user unit
                via `systemd-run --user` (#419,
                trollshell/src/plugin_launcher.rs); once running it dials
                plugin.sock and speaks the Register handshake itself
                (trollshell/src/plugins.rs).
              '';
            };

            env = lib.mkOption {
              type = lib.types.attrsOf lib.types.str;
              default = { };
              example = {
                PET_NAME = "nisse";
                PET_LLM_MODEL = "google/gemini-3.5-flash";
              };
              description = ''
                Environment variables passed to the plugin binary at launch
                (rendered into the launch-state file's per-plugin `env` map and
                applied as `--setenv=K=V` by the launcher,
                trollshell/src/plugin_launcher.rs). This is the non-secret
                sibling of `secrets` below and the idiom each bundled plugin
                reads its config through — so it is *how the non-secret runtime
                knobs are exposed as nix options* (#533): set the plugin's env
                var here rather than in a shell profile. Values must be strings.

                Do NOT put API keys here — the launch-state file is
                world-readable; use `secrets` (below) instead, which injects the
                key from the login keyring at spawn.

                A few representative examples (each also readable from the
                environment directly; the nix option is just the declarative
                way to set it):

                - `pet` (hytte-plugin-pet): `PET_NAME` (display name),
                  `PET_LLM_URL` (opt into a local llama-server brain — the API
                  *key* is a `secrets` slot, not env).
                - `usage` (hytte-plugin-usage): `TROLLSHELL_USAGE_DASHBOARD_URL`
                  (the Grafana public-dashboard URL — the value that flips the
                  card from empty-state to live).
                - `weather` (hytte-plugin-weather): `TROLLSHELL_WEATHER_CITY`
                  (geocoded fallback when GeoClue is unavailable — usually set
                  session-wide via `programs.trollshell.weather.fallbackCity`
                  instead of per-plugin here).

                The full inventory — swept from source, all 12 bundled
                plugins including the ones with zero knobs — is published at
                <https://vibec0re.github.io/trollshell/plugin-env.html>
                (source: `docs/plugin-env.md`). An absolute URL rather than a
                relative one because this description is also rendered by
                `nixos-option` and `man home-configuration.nix`, where a
                relative `plugin-env.html` link would resolve to nothing.

                Precedence for a plugin that also reads a config file (e.g.
                usage's `~/.config/trollshell/usage.toml`): environment (this
                option) wins over the file, which wins over the built-in default.
              '';
            };

            secrets = lib.mkOption {
              type = lib.types.listOf lib.types.str;
              default = [ ];
              example = [ "openrouter" ];
              description = ''
                AI-provider key *slots* to inject into this plugin at launch
                (#392). For each slot the shell reads the key stored in your
                login keyring — managed by the control-center's AI Keys tab,
                never written to disk or this config — and passes it to the
                plugin as the `<SLOT>_API_KEY` environment variable (e.g.
                "openrouter" → OPENROUTER_API_KEY), which is exactly the
                override hytte-ai-providers' `load_key` reads first. So an
                LLM-backed plugin picks the key up with no per-plugin config:
                `plugins.pet.secrets = [ "openrouter" ];`. A slot with no
                stored key is simply skipped (the plugin runs keyless and uses
                its own fallback); a plugin that doesn't list a slot never gets
                that key in its environment. Rotating a key in the
                control-center relaunches the running plugins that declare it.
              '';
            };
          };
        }
      );
      default = { };
      example = lib.literalExpression ''
        {
          # A bundled plugin, wired from this flake's per-plugin package
          # (see the list of ids in the description below):
          pet = {
            package = trollshell.packages.''${system}.hytte-plugin-pet;
            env.PET_NAME = "nisse";
          };
        }
      '';
      description = ''
        Declarative plugins (#350, launch model #419), keyed by plugin id:
        each attr drops in without hand-writing a systemd unit. The option
        renders to a JSON launch-state file
        (`trollshell/plugins.json` under XDG config — per-user via
        home-manager, /etc/xdg via the NixOS module) that the running shell
        reads at startup, launching each enabled entry as a *transient*
        `trollshell-plugin-<id>` user unit via `systemd-run --user`
        (trollshell/src/plugin_launcher.rs; Restart=on-failure, and
        `PartOf=` the session target — supervision and session lifetime
        stay systemd's job, and the launch env is where #392's key
        injection hooks in). Under home-manager that `PartOf=` is
        `programs.trollshell.systemd.target`, the same target the shell's
        own unit binds to (#707); the NixOS module declares no such option,
        so its plugins bind to graphical-session.target. Being an attrset
        of submodules (the standard
        named-instance pattern), entries merge per-field across modules —
        a second module can override one field of one plugin
        (`plugins.pet.env.PET_NAME = lib.mkForce "nisse";`) or disable it
        (`plugins.pet.enable = false;`). The launched plugin dials
        plugin.sock and registers itself; the control-center's Plugins tab
        (#348) starts/stops the transient units live, while *enablement*
        stays declared here.

        Changes apply to a **running** session (#695): the shell reconciles
        the live plugins against this file — starting what was added or
        enabled, stopping what was disabled or removed, and restarting any
        plugin whose `package`, `env` or `secrets` changed. Under
        home-manager that happens during activation (the module calls the
        shell's `Control.ReloadPlugins` after writing the file, and no-ops
        when no shell is running); with the NixOS module it happens the next
        time the shell starts, because root activation has no user session
        bus to reach the shell through. Note that a reconcile also stops a
        plugin you started by hand from the Plugins tab but left
        `enable = false` here — declared state wins.

        Each bundled plugin ships as its own package in this flake (#558), so
        `package` points straight at a `hytte-plugin-<id>` output — no
        out-of-tree derivation needed:

            plugins.pet.package = trollshell.packages.''${system}.hytte-plugin-pet;

        The bundled ids are: audio-widget, bar-clock-demo, caw, clock-demo,
        departures, infobroker, pet, preem-demo, terminal, timer, usage,
        weather (each output named `hytte-plugin-<id>`). Their per-plugin
        runtime knobs go through `env` / `secrets` above.
      '';
    };
  };
}
