{
  description = "trollshell — hytte-based Wayland desktop shell";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    treefmt-nix = {
      url = "github:numtide/treefmt-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    crane.url = "github:ipetkov/crane";
    # Only used by the flake checks (hm-module) to evaluate homeModules.default
    # against a real home-manager module set; not a runtime dependency.
    home-manager = {
      url = "github:nix-community/home-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs =
    {
      self,
      nixpkgs,
      treefmt-nix,
      crane,
      home-manager,
      ...
    }:
    let
      systems = [
        "x86_64-linux"
        "aarch64-linux"
      ];
      # The 12 bundled widget plugins (#558), by crate = binary = flake-output
      # name. Each is packaged by nix/plugin.nix (a link + install of one
      # already-compiled binary — the #530 warm-artifact pattern). Shared
      # between the `packages` output (per-plugin flake outputs, so
      # `programs.trollshell.plugins.<id>.package` has something in THIS flake to
      # point at) and the `checks` output (build coverage, #449), so the list
      # lives once. `hytte-plugin-proto` (the wire-protocol lib) and
      # `hytte-plugin` (the SDK) are not plugins and are deliberately absent.
      bundledPluginNames = [
        "hytte-plugin-audio-widget"
        "hytte-plugin-bar-clock-demo"
        "hytte-plugin-caw"
        "hytte-plugin-clock-demo"
        "hytte-plugin-departures"
        "hytte-plugin-infobroker"
        "hytte-plugin-pet"
        "hytte-plugin-preem-demo"
        "hytte-plugin-terminal"
        "hytte-plugin-timer"
        "hytte-plugin-usage"
        "hytte-plugin-weather"
      ];
      forAllSystems =
        fn:
        nixpkgs.lib.genAttrs systems (
          system:
          fn rec {
            pkgs = import nixpkgs { inherit system; };
            # crane drives the build on nixpkgs' own rust toolchain.
            craneLib = crane.mkLib pkgs;
            treefmt-eval = treefmt-nix.lib.evalModule pkgs ./nix/treefmt.nix;
          }
        );
    in
    {
      packages = forAllSystems (
        { pkgs, craneLib, ... }:
        let
          trollshell = pkgs.callPackage ./nix/package.nix { inherit craneLib; };
          # The control-center companion app (#399). Reuses the shell build's
          # shared cargoArtifacts (via trollshell.passthru) so it doesn't
          # trigger a second full deps compile.
          trollshell-control-center = pkgs.callPackage ./nix/control-center.nix {
            inherit craneLib trollshell;
          };

          # Per-plugin flake packages (#558): `packages.hytte-plugin-<id>` for
          # each of the 12 bundled plugins. Generated from `bundledPluginNames`
          # (one attr each) rather than hand-written, and reuses the shell
          # build's warm workspace artifacts via nix/plugin.nix (link + install,
          # seconds apiece — the #530 pattern).
          bundledPlugins = pkgs.lib.genAttrs bundledPluginNames (
            name: pkgs.callPackage ./nix/plugin.nix { inherit craneLib trollshell name; }
          );

          # The `hytte-infobroker` CLI (#562): the #487 consent-gated broker's
          # second `[[bin]]` (crates/hytte-plugin-infobroker/Cargo.toml — a tool,
          # not a widget plugin), used by the etc/skills/infobroker agent-bridge
          # skill. Packaged via the same nix/plugin.nix derivation as the bundled
          # plugins above, but deliberately kept OUT of `bundledPluginNames` —
          # nothing in `programs.trollshell.plugins` should point at it; install
          # it with a plain `home.packages` entry instead (see the skill docs).
          hytte-infobroker = pkgs.callPackage ./nix/plugin.nix {
            inherit craneLib trollshell;
            name = "hytte-infobroker";
            description = "trollshell consent-gated agent-bridge broker CLI (#487)";
          };

          # Autogenerated `programs.trollshell.*` options reference (#533).
          # Evaluate BOTH platform modules together: they share the
          # module-common base, deduped by its stable `key`, so the merged
          # option tree is the full cross-platform + NixOS + home-manager
          # surface in one place. `nixosOptionsDoc` renders it to CommonMark,
          # which we also wrap into a standalone HTML page via `cmark` (tiny —
          # no pandoc/Haskell closure). `_module.check = false` stops the config
          # bodies (which set options owned by nixpkgs/home-manager that we do
          # not declare here) from tripping the unknown-option check; the doc
          # only forces option *metadata*, never the config, so nothing
          # platform-specific is actually built. This is pure evaluation — it
          # does not compile the shell. Build + read with:
          #   nix build .#options-doc
          #   $BROWSER result/share/doc/trollshell/options.html   # or options.md
          options-doc =
            let
              eval = pkgs.lib.evalModules {
                specialArgs = { inherit pkgs; };
                modules = [
                  { _module.check = false; }
                  (import ./nix/hm-module.nix self)
                  (import ./nix/nixos-module.nix self)
                ];
              };
              doc = pkgs.nixosOptionsDoc {
                inherit (eval) options;
                transformOptions =
                  opt:
                  opt
                  // {
                    # Document only the shell's own options — hide the
                    # module-system internals (`_module.*`) the bare evalModules
                    # introduces. Preserve the original visibility (true /
                    # "shallow") for our options; force everything else invisible.
                    visible = if pkgs.lib.hasPrefix "programs.trollshell" opt.name then opt.visible else false;
                    # Point "Declared by" at this repo. Our `_file` values are
                    # repo-relative paths (e.g. "nix/module-common.nix"); without
                    # this, nixosOptionsDoc assumes they live under nixpkgs and
                    # links to github.com/NixOS/nixpkgs, which is wrong.
                    declarations = map (decl: {
                      name = decl;
                      url = "https://github.com/vibec0re/trollshell/blob/main/${decl}";
                    }) opt.declarations;
                  };
              };
            in
            pkgs.runCommand "trollshell-options-doc"
              {
                nativeBuildInputs = [ pkgs.cmark ];
                meta.description = "Autogenerated programs.trollshell options reference (#533)";
              }
              ''
                mkdir -p "$out/share/doc/trollshell"
                cp ${doc.optionsCommonMark} "$out/share/doc/trollshell/options.md"
                {
                  echo '<!DOCTYPE html><html lang="en"><head><meta charset="utf-8">'
                  echo '<meta name="viewport" content="width=device-width, initial-scale=1">'
                  echo '<title>trollshell — programs.trollshell options</title>'
                  echo '<style>body{max-width:55rem;margin:2rem auto;padding:0 1rem;font-family:system-ui,sans-serif;line-height:1.5}code{background:rgba(127,127,127,.15);padding:.1em .3em;border-radius:3px}pre{overflow-x:auto}h1,h2,h3{line-height:1.2}</style>'
                  echo '</head><body><h1>programs.trollshell options</h1>'
                  cmark --unsafe "$out/share/doc/trollshell/options.md"
                  echo '</body></html>'
                } > "$out/share/doc/trollshell/options.html"
              '';
        in
        {
          inherit
            trollshell
            trollshell-control-center
            options-doc
            hytte-infobroker
            ;
          default = trollshell;
        }
        // bundledPlugins
      );

      devShells = forAllSystems (
        { pkgs, ... }:
        {
          default = import ./nix/devshell.nix {
            inherit pkgs;
            trollshell = self.packages.${pkgs.stdenv.hostPlatform.system}.trollshell;
          };
        }
      );

      formatter = forAllSystems ({ treefmt-eval, ... }: treefmt-eval.config.build.wrapper);

      checks = forAllSystems (
        {
          pkgs,
          treefmt-eval,
          craneLib,
          ...
        }:
        let
          system = pkgs.stdenv.hostPlatform.system;
          trollshell = pkgs.callPackage ./nix/package.nix { inherit craneLib; };
          # The control-center companion app (#411), mirroring the `packages`
          # output above — reuses `trollshell.passthru.cargoArtifacts` so it
          # doesn't trigger a second full deps compile.
          trollshell-control-center = pkgs.callPackage ./nix/control-center.nix {
            inherit craneLib trollshell;
          };

          # The 12 per-plugin packages (#558), mirroring the `packages` output.
          # Merged into `checks` below so `nix flake check` actually *builds*
          # each one — the same reason #449 wired the two existing packages into
          # checks: flake check only builds what's listed here, so without this a
          # broken plugin package could stay green until someone ran `nix build
          # .#hytte-plugin-<id>`. Near-free: warm-artifact link + install.
          bundledPlugins = pkgs.lib.genAttrs bundledPluginNames (
            name: pkgs.callPackage ./nix/plugin.nix { inherit craneLib trollshell name; }
          );

          # The `hytte-infobroker` CLI package (#562), mirroring the `packages`
          # output above. Wired into `checks` below for the same #449 reason as
          # `bundledPlugins`: without it, `nix flake check` could stay green
          # while `nix build .#hytte-infobroker` was actually broken.
          hytte-infobroker = pkgs.callPackage ./nix/plugin.nix {
            inherit craneLib trollshell;
            name = "hytte-infobroker";
            description = "trollshell consent-gated agent-bridge broker CLI (#487)";
          };

          # A cheap stand-in for the real trollshell package so the module-eval
          # checks don't force a full Rust crate build just to type-check the
          # config bodies. It carries meta.mainProgram so `lib.getExe cfg.package`
          # (used by the systemd ExecStart) still resolves.
          stubPackage = pkgs.writeShellScriptBin "trollshell" "";

          # Stand-in plugin binary for the programs.trollshell.plugins
          # coverage in the two module-eval checks below (#350/#355).
          stubPlugin = pkgs.writeShellScriptBin "hytte-plugin-demo" "";

          # The hytte-ecal `probe` example binary + fixture sources (a
          # task-list and a calendar), for the eds-nixos-test below.
          probe = pkgs.callPackage ./nix/probe.nix { inherit craneLib; };
          # The hytte-services `wifi_probe` example binary, for the
          # wifi-nm-nixos-test below.
          wifiProbe = pkgs.callPackage ./nix/wifi-probe.nix { inherit craneLib; };
          taskSource = pkgs.writeText "test-tasks.source" ''
            [Data Source]
            DisplayName=Test Tasks
            Enabled=true

            [Task List]
            BackendName=local
          '';
          # A writable local calendar the probe seeds FREQ=DAILY;COUNT=5
          # VEVENTs into, then expands via generate_instances — exercising the
          # RRULE-expansion path (#29) and the EXDATE recurrence-set modifier
          # (the #29 follow-up: one series cancels a day via EXDATE).
          calSource = pkgs.writeText "test-calendar.source" ''
            [Data Source]
            DisplayName=Test Calendar
            Enabled=true

            [Calendar]
            BackendName=local
          '';
        in
        {
          formatting = treefmt-eval.config.build.check self;

          # `nix flake check` only *builds* the derivations listed in `checks`
          # — it does not build `packages` just because they're evaluable.
          # Without these two entries, CI (which runs flake check, not
          # `nix build`) can stay green while `nix build .#trollshell` or
          # `.#trollshell-control-center` is actually broken — the release
          # profile, `nix/package.nix`'s src filter, the assets derivation,
          # and the makeWrapper wrapper are never exercised. See #449.
          inherit trollshell trollshell-control-center hytte-infobroker;

          # Lint the entire workspace with pedantic-clean Clippy. Reuses
          # cargoArtifacts from the package build so dependencies aren't
          # recompiled from scratch. Must stay green because the workspace
          # denies clippy::all + clippy::pedantic and forbids unsafe.
          #
          # `--features system-tests` pulls the whole-file-gated integration
          # tests (crates/hytte-{bus,reactive,ui}/tests/*.rs) and the gated
          # `mod` blocks (hytte-ui's widget_tests/gtk_tests) into the lint
          # pass too — without it they're invisible to clippy, the same gap
          # #232 found for `cargo test` itself. Verified clean locally
          # (`cargo clippy --workspace --all-targets --features system-tests
          # -- -D warnings`) before wiring this in.
          clippy = craneLib.cargoClippy (
            trollshell.passthru.commonArgs
            // {
              cargoArtifacts = trollshell.passthru.cargoArtifacts;
              cargoClippyExtraArgs = "--workspace --all-targets --features system-tests -- -D warnings";
              # This is a leaf/terminal check — nothing chains off its target
              # dir as `cargoArtifacts` — so don't pack it. crane defaults
              # `doInstallCargoArtifacts = true`, which would tar the whole
              # (multi-GiB) target dir into $out for no consumer, burning build
              # time and disk. Same fix + reason as system-tests below.
              doInstallCargoArtifacts = false;
            }
          );

          # Run the `system-tests` cargo-feature bucket (#232): the
          # whole-file-`#![cfg(feature = "system-tests")]` integration tests
          # in hytte-bus/hytte-reactive/hytte-ui, plus the `#[cfg(all(test,
          # feature = "system-tests"))]` GTK unit-test modules in hytte-ui.
          # These never compile anywhere else — the package build (doCheck
          # above) deliberately omits the feature to stay hermetic — so this
          # is their only home. Built via `mkCargoDerivation` directly
          # (rather than `craneLib.cargoTest`) because `cargoTest.nix`
          # hardcodes `checkPhaseCargoCommand`, silently discarding any
          # override — we need that command to wrap `cargo test` in
          # `xvfb-run` for the GTK tests (hytte-ui's `app_smoke`/`bind`/
          # widget-tree & multi-sparkline tests) to have a display.
          # hytte-bus's tests spawn their own ephemeral `dbus-daemon`
          # (crates/hytte-bus/tests/common/mod.rs), so that binary needs to
          # be on PATH too — neither it nor `xvfb-run` are in the devShell or
          # the package's buildInputs, so both are supplied explicitly here.
          # Reuses the same cargoArtifacts as the package build/clippy: the
          # `system-tests` feature is `[]` (no extra deps), so the cached
          # dependency graph is unaffected — only the workspace members
          # themselves (not covered by cargoArtifacts, which only caches
          # true external deps) need recompiling against the extra feature.
          system-tests = craneLib.mkCargoDerivation (
            trollshell.passthru.commonArgs
            // {
              pnameSuffix = "-system-tests";
              cargoArtifacts = trollshell.passthru.cargoArtifacts;
              nativeCheckInputs = [
                pkgs.dbus
                pkgs.xvfb-run
              ];
              doCheck = true;
              # Leaf/terminal check: nothing consumes its target dir. crane
              # defaults `doInstallCargoArtifacts = true`, which packs the whole
              # ~2.2GiB target dir into a `target.tar.zst` — and that pack step
              # was OOM-ing CI's disk ("No space left on device" / "zstd: error
              # 70" in the artifact-install after every test already passed),
              # systematically failing PRs on runners with tight disks. Turning
              # it off stops producing the tarball entirely (#530: less artifact
              # churn overall).
              doInstallCargoArtifacts = false;
              # No separate build step: `cargo test` compiles as part of the
              # check phase. `commonArgs.preBuild` (the libspa-sys writable-
              # vendor-dir workaround) still runs first via the standard
              # (now-empty) buildPhase, same as it does for the `clippy` and
              # `cargoTest`-shaped checks — so the check phase's compile
              # inherits a writable vendor dir.
              buildPhaseCargoCommand = "";
              # A fresh writable $HOME: GTK/glib want to write font/icon
              # caches, and default stdenv HOME is deliberately unwritable.
              # xvfb-run allocates its own virtual display, so no manual
              # Xvfb/DISPLAY wiring is needed. Call the real `cargo` binary
              # directly (not the `cargoWithProfile` shell helper) because
              # xvfb-run execs its argv directly rather than through a
              # shell, so a bash *function* wouldn't resolve — the plain
              # `cargo` binary is on PATH via mkCargoDerivation's own
              # nativeBuildInputs and env vars (CARGO_HOME, vendoring) are
              # inherited by the child process either way.
              preCheck = ''
                export HOME="$(mktemp -d)"
              '';
              checkPhaseCargoCommand = ''
                xvfb-run -a cargo test --workspace --locked --features system-tests
              '';
            }
          );

          # Evaluate homeModules.default against a real home-manager module set so
          # the config bodies (systemd user units, session vars, the swaybg gate,
          # the awww assertion) are actually forced — not just parsed. Builds a
          # trivial derivation that deepSeq's the config attrs that hold those
          # bodies, so a broken body fails the check rather than silently lurking.
          hm-module =
            let
              hm = home-manager.lib.homeManagerConfiguration {
                inherit pkgs;
                modules = [
                  self.homeModules.default
                  {
                    home = {
                      username = "alice";
                      homeDirectory = "/home/alice";
                      stateVersion = "24.11";
                      # `nixpkgs.follows = "nixpkgs"` means HM and nixpkgs ride
                      # the same unstable channel but report different release
                      # numbers; the check is module-eval coverage, not a
                      # release-matched deployment, so silence the warning.
                      enableNixpkgsReleaseCheck = false;
                    };
                    programs.trollshell = {
                      enable = true;
                      package = stubPackage;
                      enableSessionExtras = true;
                      weather.fallbackCity = "Berlin";
                      systemd.target = "niri-session.target";
                      # plugins (#350/#355, attrsOf keyed by id): `demo` gets a
                      # unit; `off` must be filtered out by enable = false.
                      plugins = {
                        demo = {
                          package = stubPlugin;
                          env.DEMO_TOKEN = "hunter2";
                        };
                        off = {
                          package = stubPlugin;
                          enable = false;
                        };
                      };
                    };
                  }
                  # A second module contributing to the *same* plugin key —
                  # attrsOf submodules must merge per-field across modules
                  # (the point of #355), not conflict or drop an entry.
                  { programs.trollshell.plugins.demo.env.DEMO_EXTRA = "1"; }
                ];
              };
              cfg = hm.config;
              # Force the module's config bodies: the systemd user units (incl.
              # the swaybg unit the extras bundle starts under the default
              # backend), the session vars, and every assertion's *predicate* (so
              # the awww-channel assertion in hm-module.nix actually runs). Only
              # the predicates, not the messages — a message is the lazy
              # explanation shown when an assertion fails, so forcing it would be
              # both pointless and prone to evaluating intentionally-deferred text.
              units = cfg.systemd.user.services;
              # The declarative plugin launch state (#419): the module renders
              # the plugins option to trollshell/plugins.json — read back here
              # from the generated file's text — instead of emitting units.
              # fromJSON forbids string context (the exec store path), and this
              # probe only inspects the eval, so discarding it is sound here.
              pluginsState = builtins.fromJSON (
                builtins.unsafeDiscardStringContext cfg.xdg.configFile."trollshell/plugins.json".text
              );
              probe =
                # plugins (#419): entries render to the launch-state file, not
                # static units; enable = false is *declared disabled* (listed,
                # not auto-launched) rather than filtered out; and the demo
                # entry's env still merges per-field across the two modules
                # above (#355).
                assert !(units ? trollshell-plugin-demo);
                assert !(units ? trollshell-plugin-off);
                assert pluginsState.plugins.demo.exec == pkgs.lib.getExe stubPlugin;
                assert pluginsState.plugins.demo.enabled;
                assert pluginsState.plugins.demo.env.DEMO_TOKEN == "hunter2";
                assert pluginsState.plugins.demo.env.DEMO_EXTRA == "1";
                assert !pluginsState.plugins.off.enabled;
                builtins.deepSeq {
                  userUnits = units;
                  sessionVars = cfg.home.sessionVariables;
                  assertionPredicates = map (a: a.assertion) cfg.assertions;
                } "ok";
            in
            pkgs.runCommand "trollshell-hm-module-check" { inherit probe; } ''
              echo "$probe" >/dev/null
              touch $out
            '';

          # Evaluate nixosModules.default the same way. Forces the module's own
          # config contributions — the swaybg/polkit user units, the session
          # vars, and the assertions — rather than system.build.toplevel, to keep
          # it light. A blanket `deepSeq` over the whole NixOS config blows the
          # call stack (systemPackages/systemd recurse through the full package
          # closure), so we force only the trollshell-relevant slices: attrNames
          # of the service sets (which still forces every mkIf/mkMerge branch to
          # decide membership) plus the swaybg unit's ExecStart string (the actual
          # body logic) and the assertions.
          nixos-module =
            let
              nixos = nixpkgs.lib.nixosSystem {
                inherit system;
                modules = [
                  self.nixosModules.default
                  {
                    programs.trollshell = {
                      enable = true;
                      package = stubPackage;
                      weather.fallbackCity = "Berlin";
                      # plugins (#350/#355, attrsOf keyed by id): `demo` gets a
                      # unit; `off` must be filtered out by enable = false.
                      plugins = {
                        demo = {
                          package = stubPlugin;
                          env.DEMO_TOKEN = "hunter2";
                        };
                        off = {
                          package = stubPlugin;
                          enable = false;
                        };
                      };
                    };
                    # Minimal stubs so the NixOS module set evaluates without a
                    # real machine: a bootloader, a root filesystem, and a state
                    # version. nixpkgs.hostPlatform is set via nixosSystem above.
                    boot.loader.grub.enable = false;
                    fileSystems."/" = {
                      device = "/dev/sda1";
                      fsType = "ext4";
                    };
                    system.stateVersion = "24.11";
                  }
                  # A second module contributing to the *same* plugin key —
                  # attrsOf submodules must merge per-field across modules
                  # (the point of #355), not conflict or drop an entry.
                  { programs.trollshell.plugins.demo.env.DEMO_EXTRA = "1"; }
                ];
              };
              cfg = nixos.config;
              # Force the trollshell module's own outputs without descending into
              # package store closures: the unit/var/package key sets, the swaybg
              # ExecStart body, the session vars, the dbus policy package count,
              # and every assertion's boolean. We force only the assertion
              # *predicates*, not their messages — NixOS ships assertions whose
              # `message` is lazy and only well-defined when the assertion fails
              # (e.g. the fileSystems topological-sort error), so deepSeq'ing all
              # messages would trip an unrelated internal assertion's message.
              units = cfg.systemd.user.services;
              # The declarative plugin launch state (#419): the NixOS module
              # renders the plugins option to /etc/xdg/trollshell/plugins.json
              # (the $XDG_CONFIG_DIRS fallback the shell's launcher reads).
              # fromJSON forbids string context (the exec store path), and this
              # probe only inspects the eval, so discarding it is sound here.
              pluginsState = builtins.fromJSON (
                builtins.unsafeDiscardStringContext cfg.environment.etc."xdg/trollshell/plugins.json".text
              );
              probe =
                # plugins (#419): entries render to the launch-state file, not
                # static units; enable = false is *declared disabled* (listed,
                # not auto-launched) rather than filtered out; and the demo
                # entry's env still merges per-field across the two modules
                # above (#355).
                assert !(units ? trollshell-plugin-demo);
                assert !(units ? trollshell-plugin-off);
                assert pluginsState.plugins.demo.exec == pkgs.lib.getExe stubPlugin;
                assert pluginsState.plugins.demo.enabled;
                assert pluginsState.plugins.demo.env.DEMO_TOKEN == "hunter2";
                assert pluginsState.plugins.demo.env.DEMO_EXTRA == "1";
                assert !pluginsState.plugins.off.enabled;
                builtins.deepSeq {
                  userUnits = builtins.attrNames units;
                  swaybgExec = units.swaybg.serviceConfig.ExecStart;
                  sessionVars = cfg.environment.sessionVariables;
                  systemPackageCount = builtins.length cfg.environment.systemPackages;
                  dbusPackageCount = builtins.length cfg.services.dbus.packages;
                  assertionPredicates = map (a: a.assertion) cfg.assertions;
                } "ok";
            in
            pkgs.runCommand "trollshell-nixos-module-check" { inherit probe; } ''
              echo "$probe" >/dev/null
              touch $out
            '';

          # The "lean heavy on nix" counterpart to the Rust ephemeral-EDS
          # harness (#49): boot a real NixOS VM with evolution-data-server
          # configured declaratively, seed a fixture task list + calendar, and
          # run the hytte-ecal probe against it end-to-end. The probe also
          # creates FREQ=DAILY;COUNT=5 VEVENTs (one with an EXDATE) and expands
          # them, so this gates the RRULE-expansion fix for #29 and its
          # EXDATE/RDATE follow-up, plus a TZID=Europe/Berlin event whose
          # absolute instant guards the zoned-time fix (#522). Verified to run
          # under TCG (no KVM needed);
          # GitHub's Linux runners have /dev/kvm for speed.
          eds-nixos-test = pkgs.testers.runNixOSTest {
            name = "eds-nixos-test";
            nodes.machine =
              { ... }:
              {
                users.users.alice = {
                  isNormalUser = true;
                  uid = 1000;
                };
                # Three-line EDS module: installs the package, wires its D-Bus
                # session activation service files, and its systemd user units.
                services.gnome.evolution-data-server.enable = true;
                programs.dconf.enable = true; # EDS GSettings backend
                services.gnome.gnome-keyring.enable = true; # EDS credential store
                environment.systemPackages = [ probe ];
                virtualisation.graphics = false;
              };
            testScript = ''
              machine.wait_for_unit("multi-user.target")

              # Seed the fixture task-list + calendar sources into alice's home.
              machine.succeed("mkdir -p /home/alice/.config/evolution/sources")
              machine.copy_from_host(
                  "${taskSource}",
                  "/home/alice/.config/evolution/sources/test-tasks.source",
              )
              machine.copy_from_host(
                  "${calSource}",
                  "/home/alice/.config/evolution/sources/test-calendar.source",
              )
              machine.succeed("chown -R alice:users /home/alice/.config")
              # Store-copied files land read-only (0444); EDS's source
              # registry rewrites .source files on first open to add runtime
              # keys, which fails ("Permission denied") on a read-only file —
              # benign for the auto-provisioned lists but it left the seeded
              # *calendar* unwritable, so creating an event on it failed. Make
              # the fixtures writable.
              machine.succeed("chmod -R u+w /home/alice/.config/evolution")

              # Bring up alice's user session (creates /run/user/1000/bus).
              machine.succeed("loginctl enable-linger alice")
              machine.wait_for_unit("user@1000.service")
              machine.wait_for_file("/run/user/1000/bus")

              # Run the probe as alice; EDS D-Bus-activates on first connect.
              schemas = "${pkgs.evolution-data-server}/share/gsettings-schemas"
              output = machine.wait_until_succeeds(
                  "su -s /bin/sh alice -c '"
                  + "export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus; "
                  + "export HOME=/home/alice XDG_RUNTIME_DIR=/run/user/1000; "
                  + "export GSETTINGS_SCHEMA_DIR=$(ls -d " + schemas + "/*/glib-2.0/schemas | head -1); "
                  + "probe'",
                  timeout=180,
              )
              # EDS auto-provisions a default "Personal" list, so the count
              # isn't 1 — assert our seeded fixture is enumerated and the FFI
              # create/remove roundtrip actually worked.
              assert "Test Tasks" in output, output
              assert "created uid: hytte-ecal-probe-1" in output, output
              assert "removed hytte-ecal-probe-1" in output, output

              # Live view push (#33): the probe opens a CalClientView over the
              # task list, then from a *second* client connection (standing in
              # for Endeavour) creates + modifies a task. EDS must push the
              # objects-added/-modified notifications to the view — exercising
              # get_view_sync → view_start → the GObject signal trampoline →
              # the boxed Rust callback, pumped via a private GMainContext. A
              # missing push would bail the probe (so wait_until_succeeds would
              # fail); the explicit count line is the positive signal. The probe
              # watches whichever task list EDS lists first (ordering isn't
              # guaranteed — could be the auto-provisioned "Personal" or our
              # "Test Tasks"), so don't pin the name here.
              assert "watching '" in output, output
              assert "editor created uid: hytte-ecal-live-1" in output, output
              assert "editor modified uid: hytte-ecal-live-1" in output, output
              assert "live view push count:" in output, output
              # At least the create + modify pushes landed (initial population +
              # 2). Parse the final count and assert it advanced past the
              # initial-population baseline. (The match can't be None here — the
              # assert above already required the line — but guard it so the
              # test driver's type checker is satisfied.)
              import re
              m = re.search(r"live view push count: (\d+)", output)
              assert m is not None, output
              push_count = int(m.group(1))
              assert push_count >= 2, f"expected >=2 view pushes, got {push_count}: {output}"

              # Recurrence expansion (#29): the probe seeds a
              # FREQ=DAILY;COUNT=5 VEVENT and expands it over a one-month
              # window. All 5 occurrences must materialise — the whole point
              # of the fix (the old master-only path would surface just 1).
              assert "Test Calendar" in output, output
              assert "created recurring uid:" in output, output
              assert "recurring instance count: 5" in output, output
              assert "removed recurring" in output, output

              # EXDATE exclusion (#29 follow-up): the probe seeds a second
              # FREQ=DAILY;COUNT=5 series with an EXDATE cancelling Jun 3.
              # Correct expansion drops that one occurrence (4, not 5) and the
              # cancelled instant must be absent — exactly the user-visible bug
              # this fix closes (a cancelled standup still showing up).
              assert "created exdate uid:" in output, output
              assert "exdate instance count: 4" in output, output
              assert "exdate cancelled occurrence present: false" in output, output
              assert "removed exdate" in output, output

              # Zoned time (#522): a `DTSTART;TZID=Europe/Berlin:…123000` event
              # (12:30 CEST) round-tripped through EDS must expand to the
              # *absolute* instant 10:30 UTC = start_unix 1784889000 — never
              # 1784896200 (12:30 UTC), the +2h double-shift that surfaced a
              # 12:30 event as 14:30 in the Upcoming list. This is the honest
              # end-to-end guard against the pre-fix bug and against #388
              # regressing in reverse; it exercises the real backend store, not
              # just the hermetic string parser.
              assert "created tzid uid:" in output, output
              assert "tzid instance count: 1" in output, output
              assert "tzid instance start_unix: 1784889000" in output, (
                  "TZID=Europe/Berlin 12:30 must resolve to 10:30 UTC "
                  "(1784889000), not 12:30 UTC (1784896200): " + output
              )
              assert "tzid instance start_unix: 1784896200" not in output, output
              assert "removed tzid" in output, output
            '';
          };

          # The "lean heavy on nix" harness for the NetworkManager Wi-Fi
          # backend (#96): boot a real NixOS VM with NetworkManager and a pair
          # of virtual Wi-Fi radios (mac80211_hwsim), then drive wifi_nm
          # end-to-end via the wifi_probe example — backend detection, device
          # discovery, a live RequestScan, and a state read. mac80211_hwsim
          # gives NM a real (simulated) wlan device so the whole D-Bus path
          # exercises against a live daemon, not a mock. Mirrors
          # eds-nixos-test; runs under TCG (no KVM needed).
          wifi-nm-nixos-test = pkgs.testers.runNixOSTest {
            name = "wifi-nm-nixos-test";
            nodes.machine =
              { ... }:
              {
                networking.networkmanager.enable = true;
                # Two virtual 802.11 radios; NM manages the resulting wlan
                # interfaces, giving the probe a real device + AP scan path.
                boot.kernelModules = [ "mac80211_hwsim" ];
                boot.extraModprobeConfig = "options mac80211_hwsim radios=2";
                environment.systemPackages = [ wifiProbe ];
                virtualisation.graphics = false;
              };
            testScript = ''
              machine.wait_for_unit("multi-user.target")
              machine.wait_for_unit("NetworkManager.service")
              # Wait until NM has a Wi-Fi device registered (hwsim + NM takeover).
              machine.wait_until_succeeds(
                  "nmcli -t -f DEVICE,TYPE device | grep ':wifi'", timeout=60
              )

              # Run the probe as root on the system bus — drives wifi_nm against
              # the live NetworkManager.
              output = machine.wait_until_succeeds("wifi_probe", timeout=180)
              assert "backend=NetworkManager" in output, output
              assert "device=" in output, output
              assert "scan=" in output, output
              assert "networks=" in output, output
            '';
          };
        }
        // bundledPlugins
      );

      # `import … self` (not a bare path) because the module's `package` option
      # defaults to self.packages.<system>.trollshell. A bare-path module would
      # instead build via `pkgs.callPackage ./package.nix`, which needs crane
      # (craneLib) wired into the consumer's nixpkgs; threading `self` reuses the
      # package we already built here rather than pushing that onto consumers.
      nixosModules.default = import ./nix/nixos-module.nix self;

      # Curried the same way and for the same reason as the NixOS module above.
      homeModules.default = import ./nix/hm-module.nix self;
      homeManagerModules.default = self.homeModules.default;
    };
}
