# niri xdg-desktop-portal routing — see ./README.md
[preferred]
default=gnome;gtk
org.freedesktop.impl.portal.FileChooser=gnome;gtk
org.freedesktop.impl.portal.Settings=gnome;gtk
org.freedesktop.impl.portal.Screenshot=wlr
org.freedesktop.impl.portal.ScreenCast=wlr
