//! The billing guard: refuse to run if the environment could silently move
//! Claude Code off the subscription and onto metered API credits — or, since
//! #994, onto a different network endpoint, a different credential, or a
//! different subscription entirely while still looking unchanged.
//!
//! # Why this fails closed instead of scrubbing
//!
//! The design calls for these variables to be **scrubbed from the child
//! environment**. Two constraints in this tree make that unreachable from
//! inside the process:
//!
//! - `std::env::remove_var` is `unsafe` under edition 2024, and this workspace
//!   is `unsafe_code = "forbid"` (only `hytte-ecal` overrides it, for FFI).
//! - `hive_claude::Config` exposes no environment hook — its driver builds the
//!   `tokio::process::Command` itself, so there is no `env_remove` seam for a
//!   consumer to reach. (Worth an upstream ask; not worth a shim script here.)
//!
//! So the scrub happens where it *can* happen — the home-manager module's
//! rendered plugin entry (`nix/hm-module.nix`), which renders every
//! [`REDIRECT_VARS`] entry as an empty `env` value on the `claude-bridge`
//! plugin — and this module makes that scrub non-optional by refusing to
//! start when it did not take effect. (The static
//! `etc/systemd/user/trollshell-claude-bridge.service` unit, which used to
//! carry the equivalent `UnsetEnvironment=`, was retired in favour of the
//! launcher-rendered plugin entry — #890; there is no shipped unit to point
//! an operator at any more.) Failing closed is the correct direction for a
//! billing/redirect control: a bridge that will not start is loud, whereas a
//! bridge that quietly bills to metered credits, or quietly ships its traffic
//! and credential to a third-party host, is not.
//!
//! # It is scoped to the modes that spawn `claude` (#730)
//!
//! Every variable here redirects **the child**. `CLAUDE_BRIDGE_MODE=api`
//! spawns no child: it is the mode you pick *because* you want to be billed per
//! token, and `ANTHROPIC_API_KEY` is the credential it runs on rather than a
//! silent redirect away from something else. So `main` runs this guard only
//! when `Mode::spawns_claude()`, and a test there pins that scoping — if it
//! ever widened back to unconditional, the API backend could not be configured
//! through its env override at all.

/// Environment variables that would redirect the `claude` child away from the
/// subscription — either onto a different billing account, a different
/// credential, or (#994) a different network endpoint while it otherwise
/// looks unchanged. Grouped by what each one moves:
///
/// - `ANTHROPIC_API_KEY` / `ANTHROPIC_AUTH_TOKEN` — bill to metered API
///   credits instead of the OAuth subscription session.
/// - `CLAUDE_CODE_OAUTH_TOKEN` — a *different* subscription's credential.
///   Claude Code's own authentication-precedence list ranks this **above**
///   the `/login` session this bridge is meant to ride (rank 5 vs. rank 7 —
///   it wins even when a working `/login` credential is present): "A
///   long-lived OAuth token generated by `claude setup-token`. Use this for
///   CI pipelines and scripts where browser login isn't available. … reads
///   the variable again in every new session until you remove it from your
///   shell profile or the `env` block of a settings file." —
///   <https://code.claude.com/docs/en/authentication#authentication-precedence>
/// - `CLAUDE_CODE_USE_BEDROCK` / `CLAUDE_CODE_USE_VERTEX` /
///   `CLAUDE_CODE_USE_FOUNDRY` — bill to a cloud provider account entirely.
///   Foundry is documented as the third member of this set, not just the
///   first two: "Cloud provider credentials, when `CLAUDE_CODE_USE_BEDROCK`,
///   `CLAUDE_CODE_USE_VERTEX`, or `CLAUDE_CODE_USE_FOUNDRY` is set." —
///   <https://code.claude.com/docs/en/authentication#authentication-precedence>
/// - `ANTHROPIC_BASE_URL` overrides the endpoint host directly, independent
///   of every other variable in this list — it redirects even with **no**
///   other credential set: "…is the variable that
///   points Claude Code at the gateway. Setting only that variable, without a
///   gateway credential, doesn't replace the subscription. Requests still
///   route through the gateway, but a saved claude.ai login remains the
///   active credential, so its usage limits and billing apply." —
///   <https://code.claude.com/docs/en/llm-gateway#subscriptions-and-gateways>.
///   That is the exact #994 failing input:
///   `ANTHROPIC_BASE_URL=http://127.0.0.1:9999` used to start cleanly, where
///   `ANTHROPIC_API_KEY=x` already refused.
/// - `ANTHROPIC_BEDROCK_BASE_URL` / `ANTHROPIC_VERTEX_BASE_URL` — unlike
///   `ANTHROPIC_BASE_URL` above, each of these only takes effect under its
///   own `CLAUDE_CODE_USE_*` flag, which this list already catches — guarding
///   them too is belt-and-braces, not an independent gap: "Override the
///   Amazon Bedrock endpoint URL … or when routing through an LLM gateway"
///   and "Override Google Cloud's Agent Platform endpoint URL … or when
///   routing through an LLM gateway" —
///   <https://code.claude.com/docs/en/env-vars>
/// - `ANTHROPIC_FOUNDRY_BASE_URL` / `ANTHROPIC_FOUNDRY_RESOURCE` /
///   `ANTHROPIC_FOUNDRY_AUTH_TOKEN` / `ANTHROPIC_FOUNDRY_API_KEY` — the same
///   four capabilities as the entries above (an endpoint override, an
///   endpoint override, a bearer credential, and an API-key credential),
///   restated for Foundry rather than Bedrock/Vertex/the plain gateway case:
///   "Check that `ANTHROPIC_FOUNDRY_RESOURCE` is set to your actual resource
///   name … Claude Code builds the endpoint URL from this value" and "Claude
///   Code sends the value of `ANTHROPIC_FOUNDRY_AUTH_TOKEN` on every request
///   as the `Authorization: Bearer` header" —
///   <https://code.claude.com/docs/en/microsoft-foundry>
/// - `ANTHROPIC_CUSTOM_HEADERS` can set the very header `ANTHROPIC_AUTH_TOKEN`
///   sets, by another spelling — or a `Host:` override, which is a routing
///   change: "Custom headers to add to requests … A value that sets a
///   credential, org or tenant, routing, or API-behavior header, such as
///   `Authorization` or `Host`, counts as a setting that needs approval when
///   server-managed settings deliver it." —
///   <https://code.claude.com/docs/en/env-vars>
///
/// Deliberately **not** here: `CLAUDE_CODE_API_KEY_HELPER_TTL_MS` only tunes
/// how often the (settings.json-configured) `apiKeyHelper` script re-runs —
/// there is no env var that *installs* a helper, so this guard cannot cover
/// that mechanism at all. `HTTPS_PROXY`/`NO_PROXY` move the transport, not
/// the endpoint or the credential — TLS to the real host stays end-to-end and
/// nothing about which account is billed changes, so refusing on them would
/// break every legitimately-proxied user for no billing benefit.
/// `CLAUDE_CONFIG_DIR` moves where the login credential is *read from*, which
/// is itself a legitimate setting the child may need in order to find a login
/// at all; refusing on it would be a false positive against working setups.
pub const REDIRECT_VARS: [&str; 14] = [
    "ANTHROPIC_API_KEY",
    "ANTHROPIC_AUTH_TOKEN",
    "CLAUDE_CODE_OAUTH_TOKEN",
    "CLAUDE_CODE_USE_BEDROCK",
    "CLAUDE_CODE_USE_VERTEX",
    "CLAUDE_CODE_USE_FOUNDRY",
    "ANTHROPIC_BASE_URL",
    "ANTHROPIC_BEDROCK_BASE_URL",
    "ANTHROPIC_VERTEX_BASE_URL",
    "ANTHROPIC_FOUNDRY_BASE_URL",
    "ANTHROPIC_FOUNDRY_RESOURCE",
    "ANTHROPIC_FOUNDRY_AUTH_TOKEN",
    "ANTHROPIC_FOUNDRY_API_KEY",
    "ANTHROPIC_CUSTOM_HEADERS",
];

/// Variables in [`REDIRECT_VARS`] that are booleans rather than credentials,
/// so an explicit off-value is genuinely harmless and must not trip the guard
/// (a unit or profile that pins `CLAUDE_CODE_USE_BEDROCK=0` is asserting the
/// *right* thing). Every other entry — including `CLAUDE_CODE_OAUTH_TOKEN`
/// and the `*_BASE_URL`/`*_RESOURCE`/`ANTHROPIC_CUSTOM_HEADERS` family — is
/// deliberately **not** here: none of them has an "off" spelling short of
/// being unset — see [`redirects`].
const BOOLEAN_FLAGS: [&str; 3] = [
    "CLAUDE_CODE_USE_BEDROCK",
    "CLAUDE_CODE_USE_VERTEX",
    "CLAUDE_CODE_USE_FOUNDRY",
];

/// Values that read as "off" for the boolean flags above.
const OFF_VALUES: [&str; 3] = ["", "0", "false"];

/// Whether one variable's value would actually redirect billing.
fn redirects(name: &str, value: &str) -> bool {
    let trimmed = value.trim();
    if BOOLEAN_FLAGS.contains(&name) {
        !OFF_VALUES
            .iter()
            .any(|off| trimmed.eq_ignore_ascii_case(off))
    } else {
        !trimmed.is_empty()
    }
}

/// The subset of [`REDIRECT_VARS`] that `lookup` reports as set to a
/// redirecting value.
///
/// Takes the lookup as a parameter so it is testable without mutating the
/// process environment (which is `unsafe` under edition 2024) — the same shape
/// `hytte_ai_providers::load_key_from` uses for the identical reason.
pub fn offenders(lookup: impl Fn(&str) -> Option<String>) -> Vec<&'static str> {
    REDIRECT_VARS
        .into_iter()
        .filter(|name| lookup(name).is_some_and(|v| redirects(name, &v)))
        .collect()
}

/// [`offenders`] against the real process environment.
#[must_use]
pub fn offenders_in_env() -> Vec<&'static str> {
    offenders(|name| std::env::var(name).ok())
}

/// The message printed before exiting when the guard trips. Spelled out because
/// the only place anyone will read it is a `systemctl status` tail.
#[must_use]
pub fn refusal(found: &[&'static str]) -> String {
    format!(
        "refusing to start: {} set in the environment.\n\
         These would move `claude` off the Claude subscription — onto metered \
         API credits, a different subscription, a cloud provider's billing \
         (Bedrock/Vertex/Foundry), or a different endpoint entirely — without \
         any visible sign.\n\
         The nix module's rendered plugin entry scrubs these to empty; if you \
         are running the bridge by hand, unset them first.",
        found.join(", ")
    )
}

#[cfg(test)]
mod tests {
    use super::{REDIRECT_VARS, offenders, refusal};

    /// The list itself is the security control — pin it so a variable cannot be
    /// dropped from it in passing.
    #[test]
    fn the_scrub_list_is_exactly_the_fourteen_redirect_vars() {
        assert_eq!(
            REDIRECT_VARS,
            [
                "ANTHROPIC_API_KEY",
                "ANTHROPIC_AUTH_TOKEN",
                "CLAUDE_CODE_OAUTH_TOKEN",
                "CLAUDE_CODE_USE_BEDROCK",
                "CLAUDE_CODE_USE_VERTEX",
                "CLAUDE_CODE_USE_FOUNDRY",
                "ANTHROPIC_BASE_URL",
                "ANTHROPIC_BEDROCK_BASE_URL",
                "ANTHROPIC_VERTEX_BASE_URL",
                "ANTHROPIC_FOUNDRY_BASE_URL",
                "ANTHROPIC_FOUNDRY_RESOURCE",
                "ANTHROPIC_FOUNDRY_AUTH_TOKEN",
                "ANTHROPIC_FOUNDRY_API_KEY",
                "ANTHROPIC_CUSTOM_HEADERS",
            ]
        );
    }

    /// A clean environment starts.
    #[test]
    fn a_clean_environment_has_no_offenders() {
        assert!(offenders(|_| None).is_empty());
    }

    /// Any non-empty credential trips the guard.
    #[test]
    fn a_set_api_key_is_an_offender() {
        let found = offenders(|n| (n == "ANTHROPIC_API_KEY").then(|| "sk-live".to_owned()));
        assert_eq!(found, vec!["ANTHROPIC_API_KEY"]);
    }

    /// An empty credential is not a redirect — an exported-but-blank variable
    /// is what a shell profile leaves behind and Claude Code ignores it.
    #[test]
    fn a_blank_credential_is_not_an_offender() {
        assert!(offenders(|n| (n == "ANTHROPIC_AUTH_TOKEN").then(|| "   ".to_owned())).is_empty());
    }

    /// The Bedrock/Vertex/Foundry flags are booleans: an explicit off-value
    /// asserts the right thing and must not block startup.
    #[test]
    fn explicitly_disabled_cloud_provider_flags_are_not_offenders() {
        for off in ["0", "false", "FALSE", ""] {
            assert!(
                offenders(|n| n.starts_with("CLAUDE_CODE_USE_").then(|| off.to_owned())).is_empty(),
                "{off:?} should read as off"
            );
        }
    }

    /// …but any on-value is a redirect.
    #[test]
    fn enabled_bedrock_is_an_offender() {
        let found = offenders(|n| (n == "CLAUDE_CODE_USE_BEDROCK").then(|| "1".to_owned()));
        assert_eq!(found, vec!["CLAUDE_CODE_USE_BEDROCK"]);
    }

    /// #994's exact failing input: a base-URL redirect used to start cleanly
    /// where an API key already refused. `ANTHROPIC_BASE_URL` in particular is
    /// the "quietest" one — traffic and credential both move, with nothing
    /// else in the environment to suggest it.
    #[test]
    fn a_set_anthropic_base_url_is_an_offender() {
        let found =
            offenders(|n| (n == "ANTHROPIC_BASE_URL").then(|| "http://127.0.0.1:9999".to_owned()));
        assert_eq!(found, vec!["ANTHROPIC_BASE_URL"]);
    }

    /// The Bedrock/Vertex endpoint overrides are credential-style too: any
    /// non-empty value is an offender, with no boolean off-value carve-out.
    #[test]
    fn the_cloud_base_url_overrides_are_offenders_when_set() {
        for name in ["ANTHROPIC_BEDROCK_BASE_URL", "ANTHROPIC_VERTEX_BASE_URL"] {
            let found = offenders(|n| (n == name).then(|| "https://evil.example".to_owned()));
            assert_eq!(found, vec![name], "{name}");
        }
    }

    /// An empty base-URL variable is what an unset-but-exported shell profile
    /// entry (or this crate's own home-manager scrub) leaves behind, and must
    /// not trip the guard.
    #[test]
    fn an_empty_base_url_is_not_an_offender() {
        for name in [
            "ANTHROPIC_BASE_URL",
            "ANTHROPIC_BEDROCK_BASE_URL",
            "ANTHROPIC_VERTEX_BASE_URL",
        ] {
            assert!(
                offenders(|n| (n == name).then(String::new)).is_empty(),
                "{name}"
            );
        }
    }

    /// `CLAUDE_CODE_OAUTH_TOKEN` outranks the `/login` subscription in Claude
    /// Code's own authentication precedence, so a stray export of it is
    /// strictly the same class of danger as `ANTHROPIC_API_KEY`.
    #[test]
    fn a_set_oauth_token_is_an_offender() {
        let found =
            offenders(|n| (n == "CLAUDE_CODE_OAUTH_TOKEN").then(|| "sk-ant-oat-...".to_owned()));
        assert_eq!(found, vec!["CLAUDE_CODE_OAUTH_TOKEN"]);
    }

    /// The Foundry family (two endpoint overrides, two credentials) is
    /// credential-style like every other entry in the list — any non-empty
    /// value is an offender, no boolean carve-out.
    #[test]
    fn the_foundry_family_is_offenders_when_set() {
        for name in [
            "ANTHROPIC_FOUNDRY_BASE_URL",
            "ANTHROPIC_FOUNDRY_RESOURCE",
            "ANTHROPIC_FOUNDRY_AUTH_TOKEN",
            "ANTHROPIC_FOUNDRY_API_KEY",
        ] {
            let found = offenders(|n| (n == name).then(|| "evil".to_owned()));
            assert_eq!(found, vec![name], "{name}");
        }
    }

    /// `ANTHROPIC_CUSTOM_HEADERS` can carry an `Authorization` or `Host`
    /// override, so it is guarded the same as the credential it can spell.
    #[test]
    fn a_set_custom_headers_is_an_offender() {
        let found = offenders(|n| {
            (n == "ANTHROPIC_CUSTOM_HEADERS").then(|| "Authorization: Bearer evil".to_owned())
        });
        assert_eq!(found, vec!["ANTHROPIC_CUSTOM_HEADERS"]);
    }

    /// Empty is unset for every new entry too, matching the home-manager
    /// scrub's `--setenv=K=` contract.
    #[test]
    fn an_empty_value_is_not_an_offender_for_any_new_entry() {
        for name in [
            "CLAUDE_CODE_OAUTH_TOKEN",
            "ANTHROPIC_FOUNDRY_BASE_URL",
            "ANTHROPIC_FOUNDRY_RESOURCE",
            "ANTHROPIC_FOUNDRY_AUTH_TOKEN",
            "ANTHROPIC_FOUNDRY_API_KEY",
            "ANTHROPIC_CUSTOM_HEADERS",
        ] {
            assert!(
                offenders(|n| (n == name).then(String::new)).is_empty(),
                "{name}"
            );
        }
    }

    /// Every offender is named in the refusal, so `systemctl status` says which
    /// one to unset.
    #[test]
    fn the_refusal_names_every_offender() {
        let found = vec!["ANTHROPIC_API_KEY", "CLAUDE_CODE_USE_VERTEX"];
        let msg = refusal(&found);
        assert!(msg.contains("ANTHROPIC_API_KEY"));
        assert!(msg.contains("CLAUDE_CODE_USE_VERTEX"));
        assert!(msg.contains("unset them first"));
        assert!(msg.contains("plugin entry"));
    }
}
